### PR TITLE
Make "apparmor" build

### PR DESCRIPTION
**Pull request by lslezak**

### CODE REVIEW

**Comment by jreidinger** [comment]
@lslezak I will fix it in upstream in few minutes, I already face it and just not find time to fix it

**Comment by jreidinger** [comment]
@lslezak upstream fixed, so patch should not be needed now

**Comment by lslezak** [comment]
Thanks, I'll adapt it.

**Comment by lslezak** [comment]
Closing, not needed anymore, after removing the symlink patch the PR becomes empty...

**Pull request closed without merging**
