### PR TITLE
Added multi threading support for faster ruby conversion step

### PR DESCRIPTION
**Pull request by lslezak**
Use all available CPU cores for faster ruby conversion, divide the conversion task across all CPUs.

Adapted displaying progress to not mix outputs from multiple threads.

On my machine with 4 cores it speeds up `yk convert network` from 1:36 to 0:40, i.e. **the speed up factor is 2.4**, that's pretty nice.

Please review, I'm not a multihreading expert ;-)

### CODE REVIEW

**Comment by lslezak** [comment]
BTW on my more powerful workstation (4C 8T CPU), the speedup is about **3.0** :-)

**Comment by dmajda** [comment]
I like the idea of speeding up the conversion, but I don't like some aspects of the implementation.
1. The messaging modification in `handle_exception` is a hack — the problem of interleaving messages should be solved on a different level  (probably the `Message` module) so that other code would not need to be modified at all. 
2. I'd abstract the parallelization into some helper. Unless a parallelizing a piece of code means something more than  wrapping the code in a block (see example below), we are doing it wrong. In my opinion it's quite important to abstract this so the code can be used for other parts of the script as well and the concerns are clearly separated.
   
   ``` ruby
   parallel do
     # code that runs in threads
   end
   ```
3. I'd like to have manual control over the parallelization (number of used CPUs), at least a an option. For example, when I run `yk ruby all`, I **don't** want all CPUs on my workstation to be used because I will do something else while the conversion is in progress.

Let's wait for @jreidinger and discuss this more.

**Comment by jreidinger** [comment]
In general I like idea of multithread use.
I agree with dmajda, that problem of reporting status in handle exception should be solved better way ( like define phase in each subclass and do it abstractly ).
I also agree that regulation of cpu number would be nice, but it is feature not bug :)
abstract parallel is fine from my POV

**Comment by dmajda** [comment]
OK. Let's discuss this in person on Monday, I have some specific ideas regarding how to handle messaging.

**Comment by lslezak** [comment]
I'll open a new PR with updated code...

**Pull request closed without merging**
