### PR TITLE
Adds ruby conversion dependencies

### PR DESCRIPTION
**Pull request by jreidinger**
It allows to handle cases where for compilation is needed one set of
dependencies and clients require additional modules, but it cannot be
added to compile dependencies as it cause circle.

### CODE REVIEW

**Comment by mvidner** [comment]
README.md needs to be updated.

**Comment by dmajda** [comment]
This pull request contains at least 3 things tangled together in one commit:
1. Split the `compile` command into `ybc` and `ruby`.
2. Rename `deps` to `ybc_deps`.
3. Add `ruby_deps` and make the `ruby` command use them instead/in addition to `ybc_deps`.

These things should be each in a separate commit, each one being one logical step toward the final state. That way, if would be easy to verify that each step is done correctly and nothing has been missed. I find that too time- and energy-consuming with the current commit.

@jreidinger Please split the work as suggested (or maybe in some other way that makes more sense to you).
@mvidner If you are willing to review this as it is, I am OK with that.

**Comment by mvidner** [comment]
> 1. Split the `compile` command into `ybc` and `ruby`.
> 2. Rename `deps` to `ybc_deps`.
> 3. Add `ruby_deps` and make the `ruby` command use them instead/in addition to `ybc_deps`.

Right. The rename (2) is simple enough and could even remain squashed, but the other two changes are hard to review if they are mixed. Please split them.

**Comment by jreidinger** [comment]
updated in https://github.com/yast/ycp-killer/pull/214

**Pull request closed without merging**
