### PR TITLE
use %fdupes macro in yast2.spec

### PR DESCRIPTION
**Pull request by lslezak**
to symlink yardoc duplicates in yast2-devel-doc package

Saves over 2MB in installed system, the RPM package is almost the same size (because of the compression).

### CODE REVIEW

**Comment by dmajda** [comment]
LGTM, but I'd like @mvidner to also have a look.

**Comment by mvidner** [comment]
I don't have experience with `fdupes`. It looks like a simple solution which we can try and if there are problems then remove it. -> LGTM

BTW I expect the generated docs will be reorganized a bit once we work on continuously producing an online version.

**Comment by dmajda** [comment]
OK, merging.

**Comment by lslezak** [comment]
BTW more details about `%fdupes` can be found on the wiki: http://en.opensuse.org/openSUSE:Packaging_Conventions_RPM_Macros#.25fdupes

**Pull request merged**
