### PR TITLE
perl-bindings - ignore source line numbers

### PR DESCRIPTION
**Pull request by lslezak**
tests should not fail if a source line number is changed,
only the result values should matter

### CODE REVIEW

**Comment by lslezak** [comment]
This is a better fix compared to #553 (more generic, ignore the source line numbers completely)

**Comment by jreidinger** [comment]
I agree that it is better, I just need to discuss it with @mvidner how he likes it. (checking lines of logs looks like really unfriendly to refactoring :smiley:

**Comment by dmajda** [comment]
Per agreement with @jreidinger I merged #553 to fix the immediate issue. With this patch let's wait for @mvidner (he's still sick).

**Comment by mvidner** [comment]
Yes, line numbers should be ignored. This patch shows even some old code trying to do that, I'll check why it fails.

**Comment by mvidner** [comment]
Fixed upstream instead.

**Pull request closed without merging**
