### PR TITLE
Remove patches for disabling autodocs, it now works correctly

### PR DESCRIPTION
**Pull request by lslezak**
Fix the path to *.pm and *.h files where needed

### CODE REVIEW

**Comment by lslezak** [comment]
JFYI: I tested conversion of all modules and it passes completely.

**Comment by mvidner** [comment]
OK, but still there are some interesting differences. I can't get Github show them nicely, so look at this locally:

```
git diff mvidner/reenable-empty-autodocs..lslezak/enable_autodocs
```
- add-on.patch you remove the part which I missed, good
- boot-server.patch you keep the bit which seems like an oversight
- heartbeat.patch likewise

**Comment by lslezak** [comment]
@mvidner Thanks for comparing the patches, I have fixed `boot-server.patch`, `heartbeat.patch` and further comparing also found that `phone-services.patch` was broken as well.

The pull request has been updated.

**Comment by mvidner** [comment]
Now I've gone through the entire diff and just installation.patch is left.

**Comment by mvidner** [comment]
Looks Good Now.

**Pull request merged**
