### PR TITLE
Stub MasterCFParser.pm

### PR DESCRIPTION
**Pull request by dmajda**
Stubbed because otherwise the "mail" YaST module will attempt to load
this file from the system, where it is broken.

### CODE REVIEW

**Comment by mvidner** [comment]
Weird. It is not broken here:

```
mvidner@mrakoplas:~$ rpm -qf /usr/lib/YaST2/servers_non_y2/MasterCFParser.pm
yast2-mail-2.21.1-173.1.noarch
mvidner@mrakoplas:~$ perl -c /usr/lib/YaST2/servers_non_y2/MasterCFParser.pm
/usr/lib/YaST2/servers_non_y2/MasterCFParser.pm syntax OK
```

**Comment by mvidner** [comment]
Ah, I had some older version from YaST:Head(?). Indeed, it is a broken update package yast2-mail-2.21.1-9.5.,1 https://bugzilla.novell.com/show_bug.cgi?id=800788#c18 :-(

**Comment by mvidner** [comment]
Please add the bug number to the stub so that we know when it can be removed again.

**Comment by dmajda** [comment]
Bug reference added in 2b639f455492484ac5fe57c298c91bdfb8f6375f. Thanks for finding the bug.

**Pull request merged**
