### PR TITLE
add `yk test` to run upstream tests

### PR DESCRIPTION
**Pull request by mvidner**
Note that I am not happy with the logging code+output but here it is so you can try the testing. Suggestions are welcome.

### CODE REVIEW

**Comment by mvidner** [comment]
I ran it on:
- http-server - does not need testedfiles
- sysconfig - should be fixed by testedfiles
- yast2 - fun! in the dwarf fortress sense: many failures

**Comment by jreidinger** [comment]
LGTM for me. I let @dmajda to also comment it

**Comment by mvidner** [comment]
amendments done

**Comment by dmajda** [comment]
Squash it? At least parts that concern `yk test`? (The rest should be in a different pull request anyway...)

**Comment by mvidner** [comment]
OK, squashed.

**Pull request merged**
